name: hello
on:
    push:
        branches: [main]
      
jobs:
    greet:
        runs-on: ubuntu-latest
        steps:
            - name: say hello to users 
              run: echo "hello dosto"

            - name: what is your name 
              run: echo "Hello $USER"
    details:
         runs-on: ubuntu-latest
         steps:
             - name: check version
               run: version --docker && version --python 
             
